### ISSUE TITLE
OpenCV's HoughCircles API.

### ISSUE THREAD

**Issue by likexin92** [AdityaMulgundkar/flutter_opencv#1]
I have a requirement to use hough transform to detect circles. How can I do that with opencv? OpenCV's HoughCircles API.

**Comment by AdityaMulgundkar** [comment]
Hi, Hough Transforms have been left out in the current build since it requires drawing in the image & those extra functions too need to be written.
I'm marking this as a feature request & trying to implement the same right now. I'll update you here if it works out.

**Comment by likexin92** [comment]
thanks，really looking forward to！

**Comment by AdityaMulgundkar** [comment]
Hi @likexin92. I have just updated the plug-in to `v1.0.2`. And I have successfully added the HoughCircles function to it. 
Usage:
```dart
// function cvtColor will take the file as bytes & ImgProc.colorBGR2GRAY, since you need to gray the image out first.
dynamic res = await ImgProc.cvtColor(await file.readAsBytes(), ImgProc.colorBGR2GRAY);
// function houghCircles will take in the file as bytes, cvHoughGradient (which = 3 by default in OpenCV), dp, minDist, param1, param2, minRadius, maxRadius
res = await ImgProc.houghCircles(await res, ImgProc.cvHoughGradient, 2.1, 0.1, 150, 100, 0, 0);
```

All the values passed to the function are taken from the OpenCV documentation, so you'll have to refer to that in order to get your perfect output, but here's a sample:

![screen_hough](https://user-images.githubusercontent.com/11910885/79572694-03e8c100-80db-11ea-973d-29b2ed0bc504.jpg)

A couple of things to note here:

- The plug-in works at the main thread, which will have to be changed to a separate thread later on (I'll update it in v1.1.0 maybe.), so, for now, larger tasks feel a little laggy (although I haven't faced lag with any of the examples yet). If you cascade too many tasks in succession, it might get delayed to a second or two, but nothing should break. 
- I haven't documented anything yet - even the houghCircles function. So I'll have to do that first, then go back to writing functions for "drawing" on top of images; hough lines; etc. 

Hope you find this useful. I'm closing the issue, for now, feel free to reopen in case you're stuck anywhere!

**Comment by sonnyproto** [comment]
Hi, Mr Aditya Mulgundkar, is there any way to get the detected circles' radius only instead of the whole processed output picture?
