### ISSUE TITLE
Add support of Hough Lines

### ISSUE THREAD

**Issue by J-x-D** [AdityaMulgundkar/flutter_opencv#5]
In my project, I would need line detection. Therefore it would be awesome if you could extend the library with the houghLines-function as you already did with the houghCirlces-function. 

The feature is implemented in the Andoird/IOS/Python libraries of open OpenCV ([here](https://docs.opencv.org/4.3.0/d9/db0/tutorial_hough_lines.html)) and allows detecting lines.
A solution should look like the pictures described in their documentation.

**Comment by AdityaMulgundkar** [comment]
Hi @J-x-D, Sorry for the late reply. I actually missed the notification generated by this issue.

Nevertheless, I'm currently working on a stable iOS build along with all base drawing features. I'll check if I can implement houghLines in the current version & push that out (without the newer planned features) immediately. 

I'll drop you a message here once I push another version out.

**Comment by ghost** [comment]
I'd appreciate some hough lines too

**Comment by ventr1x** [comment]
@AdityaMulgundkar To just hijack this issue because it's been mentioned:
Are you still actively interested in this plugin? Do you need help, especially for the iOS part (how is that coming along?)?.

I'm currently planning a computer vision heavy project that likely needs opencv and I'm either integrating opencv myself or helping with this project. But I need to move faster than an update every two months.

I also do not mind to sponsor some development time if that would motivate you.

**Comment by AdityaMulgundkar** [comment]
@ventr1x Hey. I agree that my current speed is pretty slow. I won't bother you with the specifics/reasons, but I sure do need a lot of help managing this:

- I tried building a basic ios version of the plugin on Codemagic, but my hours ran out pretty quickly due to some caching issue. Turns out they only gave ~500 mins a month for free. I tried contacting them multiple times for an open-source account as listed on their pricing page, but that simply doesn't work (yet)
- I do not own a Mac, I might be able to buy one soon, for my work, but that's not something I expect others using this plug-in to cling on to. I would love to be able to get more people on board the project & have others fork it, write their own code, review, merge, etc to help me speed up the process.
- I see that many people are using the library, and even making changes for their own purpose, but there's no mechanism to immediately drive development on a daily basis here. Do you have any ideas? I can put in a 4-6 hours a week tops, but that's assuming I'm building the correct (necessary) features in - and not the bells & whistles.
- If you, or someone else reading this wants to actively contribute to the project, I would love to setup some mechanism - some channel for communication like Slack, Discourse, etc; integrating bots for checking PR quality, for setting reminders on issues, etc. We can also do stand-ups at the end of every week/month to check on progress (if any). What do you think?
- Last, I'm unsure if I'm spending enough time on developing this project right now - and if setting a sponsorship mechanism/ github button for that in the repository would be wise. Thoughts?

I really appericiate the fact that you're here to help me out, and I'd love to get your thoughts/opinions on this. If you feel there are parts that I'm managing/doing incorrectly, I need you to be open & point those out too - whatever works best for the plugin/project.

**Comment by Gyoko** [comment]
@AdityaMulgundkar 
You can set up a ko-fi account for tips or sponsorship, as you call it. I'm pretty sure there are lots of people needing iOS version of this.  
Discord for the project would be nice, I guess.

**Comment by AdityaMulgundkar** [comment]
Hey @J-x-D @anotherdeveloper @ventr1x @Gyoko 
This was updated in opencv: 1.0.4. Please update to this version and test it out!
